### ISSUE TITLE
How is train.txt generated in dataset? Thank you

### ISSUE THREAD

**Issue by MichaelCong** [anvien/Mutli-YOLOv3#3]
How is train.txt generated in dataset? Thank you

**Comment by anvien** [comment]
You can refer the script in Toolkits/coco_annotation.py. Each line in train.txt contains a whole description of a lablled sample, it looks like the format of : (Assume that two objects (class_index1, class_index2) in an image.)
**image_path left_x1, top_y1, right_x1, bottom_y1, class_index1 left_x2, top_y2, right_x2, bottom_y2, class_index2**

**Comment by zhanganguo** [comment]
> How is train.txt generated in dataset? Thank you

You can refer the script in Toolkits/coco_annotation.py. Each line in train.txt contains a whole description of a lablled sample, it looks like the format of : (Assume that two objects (class_index1, class_index2) in an image.)
**image_path left_x1, top_y1, right_x1, bottom_y1, class_index1 left_x2, top_y2, right_x2, bottom_y2, class_index2**
for example:

D:/trainset/00001.jpg 10,15,100,204,1 302,103,402,300,2
