### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by ssswww4444** [anvien/Mutli-YOLOv3#5]
Can't train with train_YOLOv3_MultiGPU.py. 
The process gets killed by out-of-memory handler, even with batch size 1.
train.py in the original repository works well. 
Any one knows how to fix this?

**Comment by ssswww4444** [comment]
Solved. Didn't have enough CPU memory.

**Comment by an1018** [comment]
@ssswww4444
I had the same problem. How did you solve it?
Thx.
